address = "10.0.10.2/24"
if_name = "cp1"
recv_addresses = ["10.0.1.2:5000", "10.0.1.2:5001"]

[[recv_tunnels]]
key = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE="
endpoints = [{ id = 1 }, { id = 2 }]

[[send_tunnels]]
local_addresses = ["10.0.1.2:5000", "10.0.1.2:5001"]
key = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI="
endpoints = [
    { id = 1, address = "10.0.1.1:5000" },
    { id = 2, address = "10.0.1.1:5001" },
]
