address = "10.0.10.2/24"
if_name = "cp1"
private_key = "QJVxWbA6o/3kk5znUyD5rySYe+yG829uGNoh2PNVyxk="
local_control_address = "10.0.1.2:5000"

[[peers]]
public_key = "Gb1SnzVaODF8LHKoBD+dJtS/e/9GYEhnLX0sOk8OIbA="
remote_control_address = "10.0.1.1:5000"
local_tunnel_addresses = ["10.0.1.2:5010", "10.0.1.2:5011"]