address = "10.0.10.1/24"
if_name = "cp1"
private_key = "hteZOax4E+ELo6q5eSVoFAhh9awJudkYhzUJDvguNU0="
local_control_address = "10.0.1.1:5000"

[[peers]]
public_key = "Wx0KV+g6TkuSIbUF/FUEztkchnRw7akTxJ8JV8QcJi0="
remote_control_address = "10.0.1.2:5000"
local_tunnel_addresses = ["10.0.1.1:5010", "10.0.1.1:5011"]