address = "10.0.10.2/24"
private_key = "QJVxWbA6o/3kk5znUyD5rySYe+yG829uGNoh2PNVyxk="
recv_addrs = ["10.0.1.2:5000"]
interface_name = "cp1"

[[peers]]
public_key = "Gb1SnzVaODF8LHKoBD+dJtS/e/9GYEhnLX0sOk8OIbA="
local_addrs = ["10.0.1.2:5000"]
remote_addrs = ["10.0.1.1:5000"]