[package]
name = "centipede_router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.6.0"
centipede_proto = { version = "0.1.0", path = "../centipede_proto" }
chacha20poly1305 = "0.10.1"
