[package]
name = "centipede_proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20poly1305 = { version = "0.10.1", features = ["std"] }
serde = { version = "1.0.193", features = ["derive"] }
thiserror = "1.0.50"
x25519-dalek = { version = "2.0.0", features = ["serde"] }
