[package]
name = "centipeded"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.7"
centipede_router = { version = "0.1.0", path = "../centipede_router" }
centipede_worker = { version = "0.1.0", path = "../centipede_worker" }
centipede_control = { version = "0.1.0", path = "../centipede_control" }
clap = { version = "4.5.4", features = ["derive"] }
log = { version = "0.4.21", features = ["release_max_level_debug"] }
pretty_env_logger = "0.5.0"
rand = "0.8.5"
hypertube = "0.2.2"
mio = "0.8.11"
ctrlc = "3.4.4"
miette = { version = "7.2.0", features = ["fancy"] }
thiserror = "1.0.58"
